export type iCourse = {
  id: string;
  name: string;
  photo: string;
  url: string;
  desc?: string;
  type: "EAD" | "Presencial"
  certificate?: "Licenciatura" | "Superior Tecnológico" | "Bacharelado" | "2ª Licenciatura" | "Licenciatura" | "Formação Pedagógica"
};

export const coursesIn: iCourse[] = [
  {
    id: "admin-in",
    name: "Administração",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/adm.jpg",
    url: "https://oficial.unimar.br/cursos/administracao/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "ads-in",
    name: "Análise e desenvolvimento de sistemas",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/ands-e1644500942830.jpg",
    url: "https://oficial.unimar.br/cursos/analise-e-desenvolvimento-de-sistemas/",
    type: "Presencial",
    certificate: "Superior Tecnológico",
  },
  {
    id: "arq-in",
    name: "Arquitetura e Urbanismo",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/arq.jpg",
    url: "https://oficial.unimar.br/cursos/arquitetura-e-urbanismo/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "cienc-comp-in",
    name: "Ciência da Computação",
    photo: "https://oficial.unimar.br/wp-content/uploads/2022/08/ciencia-da-computacao-2-e1661889313598.jpg",
    url: "https://oficial.unimar.br/cursos/ciencia-da-computacao/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "biomed-in",
    name: "Biomedicina",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/biomed.jpg",
    url: "https://oficial.unimar.br/cursos/biomedicina/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "cienc-cont-in",
    name: "Ciência Contábeis",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/contabeis-2.jpg",
    url: "https://oficial.unimar.br/cursos/ciencias-contabeis/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "dir-in",
    name: "Direito",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/direito.jpg",
    url: "https://oficial.unimar.br/cursos/direito/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "ed-fis-in",
    name: "Educação Física",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/edfisica-1.jpg",
    url: "https://oficial.unimar.br/cursos/educacao-fisica/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "enf-in",
    name: "Enfermagem",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/enf.jpg",
    url: "https://oficial.unimar.br/cursos/enfermagem/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "eng-agro-in",
    name: "Engenharia Agronômica",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/engagro.jpg",
    url: "https://oficial.unimar.br/cursos/engenharia-agronomica/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "eng-civ-in",
    name: "Engenharia Civil",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/engcivil.jpg",
    url: "https://oficial.unimar.br/cursos/engenharia-civil/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "eng-prod-mec-in",
    name: "Engenharia de Produção Mecânica",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/edprod.jpg",
    url: "https://oficial.unimar.br/cursos/engenharia-de-producao-mecanica/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "eng-elet-in",
    name: "Engenharia Elétrica",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/engeletrica.jpg",
    url: "https://oficial.unimar.br/cursos/engenharia-eletrica/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "farm-in",
    name: "Farmácia",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/farmaciaa.jpg",
    url: "https://oficial.unimar.br/cursos/farmacia/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "fisio-in",
    name: "Fisioterapia",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/fisio.jpg",
    url: "https://oficial.unimar.br/cursos/fisioterapia/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "med-in",
    name: "Medicina",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/07/medicina-1.jpg",
    url: "https://oficial.unimar.br/cursos/medicina/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "med-vet-in",
    name: "Medicina Veterinária",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/vet.jpg",
    url: "https://oficial.unimar.br/cursos/medicina-veterinaria/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "nut-in",
    name: "Nutrição",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/nutricao.jpg",
    url: "https://oficial.unimar.br/cursos/nutricao/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "odon-in",
    name: "Odontologia",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/odonto-1.jpg",
    url: "https://oficial.unimar.br/cursos/odontologia/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "psico-in",
    name: "Psicologia",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/psico-e1595345018825.jpg",
    url: "https://oficial.unimar.br/cursos/psicologia/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
  {
    id: "publi-in",
    name: "Publicidade e Propaganda",
    photo: "https://oficial.unimar.br/wp-content/uploads/2019/08/pp.jpg",
    url: "https://oficial.unimar.br/cursos/publicidade-e-propaganda/",
    type: "Presencial",
    certificate: "Bacharelado",
  },
]

export const coursesOut: iCourse[] = [
  {
    id: "admin-out",
    name: "Administração",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/administracao.jpg.webp",
    url: "https://ead.unimar.br/cursos/administracao/",
    type: "EAD",
    certificate: "Bacharelado",
  },
  {
    id: "agro-eco-out",
    name: "Agroecologia",
    photo: "https://ead.unimar.br/wp-content/uploads/2022/11/agroecologia.jpg",
    url: "https://ead.unimar.br/cursos/agroecologia/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "ads-out",
    name: "Análise e Desenvolvimento de Sistemas",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/ads.jpg",
    url: "https://ead.unimar.br/cursos/analise-e-desenvolvimento-de-sistemas/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "cienc-cont-out",
    name: "Ciências Contábeis",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/contabeis.jpg.webp",
    url: "https://ead.unimar.br/cursos/ciencias-contabeis/",
    type: "EAD",
    certificate: "Bacharelado",
  },
  {
    id: "cienc-dad-out",
    name: "Ciências de Dados",
    photo: "https://ead.unimar.br/wp-content/uploads/2022/11/ciencias-de-dados.jpg",
    url: "https://ead.unimar.br/cursos/ciencias-de-dados/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "ed-fis-out",
    name: "Educação Física",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/edfiica.jpg",
    url: "https://ead.unimar.br/cursos/educacao-fisica/",
    type: "EAD",
    certificate: "Bacharelado",
  },
  {
    id: "empre-out",
    name: "Empreendedorismo",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/empreendedorismo.jpg.webp",
    url: "https://ead.unimar.br/cursos/empreendedorismo/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "eng-civ-out",
    name: "Engenharia Civil",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/eng-civil.jpg.webp",
    url: "https://ead.unimar.br/cursos/engenharia-civil/",
    type: "EAD",
    certificate: "Bacharelado",
  },
  {
    id: "eng-comp-out",
    name: "Engenharia de Computação",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/engenharia-da-computacao.jpg",
    url: "https://ead.unimar.br/cursos/engenharia-de-computacao/",
    type: "EAD",
    certificate: "Bacharelado",
  },
  {
    id: "eng-prod-out",
    name: "Engenharia de Produção",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/engenharia-de-producao.jpg.webp",
    url: "https://ead.unimar.br/cursos/engenharia-de-producao/",
    type: "EAD",
    certificate: "Bacharelado",
  },
  {
    id: "eng-elet-out",
    name: "Engenharia Elétrica",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/engenharia-eletrica.jpg",
    url: "https://ead.unimar.br/cursos/engenharia-eletrica/",
    type: "EAD",
    certificate: "Bacharelado",
  },
  {
    id: "este-cosm-out",
    name: "Estética e Cosmética",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/estatica-e-cosmetica.jpg.webp",
    url: "https://ead.unimar.br/cursos/estetica-e-cosmetica/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "gastr-out",
    name: "Gastronomia",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/gastronomia.jpg",
    url: "https://ead.unimar.br/cursos/gastronomia/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "gest-amb-out",
    name: "Gestão Ambiental",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/gestao-ambiental.jpg",
    url: "https://ead.unimar.br/cursos/gestao-ambiental/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "gest-com-out",
    name: "Gestão Comercial",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/gestao-comercial.jpg.webp",
    url: "https://ead.unimar.br/cursos/gestao-comercial/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "gest-agro-out",
    name: "Gestão de Agronegócios",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/gestao-de-agronegocios.jpg",
    url: "https://ead.unimar.br/cursos/agronegocios/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "gest-prod-ind-out",
    name: "Gestão de Produção Industrial",
    photo: "https://ead.unimar.br/wp-content/uploads/2022/11/gestao-producao-industrial.jpg",
    url: "https://ead.unimar.br/cursos/gestao-da-producao-industrial/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "gest-qual-out",
    name: "Gestão de Qualidade",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/gestao-de-qualidade.jpg.webp",
    url: "https://ead.unimar.br/cursos/gestao-de-qualidade/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "gest-rh-out",
    name: "Gestão de Recursos Humanos",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/RH.jpg.webp",
    url: "https://ead.unimar.br/cursos/gestao-de-recursos-humanos/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "gest-seg-priv-out",
    name: "Gestão de Segurança Privada",
    photo: "https://ead.unimar.br/wp-content/uploads/2022/11/gestao-seguranca-privada.jpg",
    url: "https://ead.unimar.br/cursos/gestao-e-seguranca-privada/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "gest-finan-out",
    name: "Gestão Financeira",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/gestao-financeira.jpg.webp",
    url: "https://ead.unimar.br/cursos/gestao-financeira/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "gest-hosp-out",
    name: "Gestão Hospitalar",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/gestao-hospital.jpg.webp",
    url: "https://ead.unimar.br/cursos/gestao-hospitalar/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "gest-public-out",
    name: "Gestão Pública",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/gestao-publica.jpg.webp",
    url: "https://ead.unimar.br/cursos/gestao-publica/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "hist-out",
    name: "História",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/historia.jpg",
    url: "https://ead.unimar.br/cursos/historia-formacao-pedagogica/",
    type: "EAD",
    certificate: "Formação Pedagógica",
  },
  {
    id: "hist-2-lic-out",
    name: "História",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/historia.jpg",
    url: "https://ead.unimar.br/cursos/historia-2a-licenciatura/",
    type: "EAD",
    certificate: "2ª Licenciatura",
  },
  {
    id: "hist-lic-out",
    name: "História",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/historia.jpg",
    url: "https://ead.unimar.br/cursos/historia/",
    type: "EAD",
    certificate: "Licenciatura",
  },
  {
    id: "jog-dig-out",
    name: "Jogos Digitais",
    photo: "https://ead.unimar.br/wp-content/uploads/2022/11/jogos-digitais.jpg",
    url: "https://ead.unimar.br/cursos/jogos-digitais/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "let-ing-port-out",
    name: "Letras Português/Inglês",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/letras_.jpg",
    url: "https://ead.unimar.br/cursos/letras-portugues-ingles-formacao-pedagogica/",
    type: "EAD",
    certificate: "Formação Pedagógica",
  },
  {
    id: "let-ing-port-2-lic-out",
    name: "Letras Português/Inglês",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/letras_.jpg",
    url: "https://ead.unimar.br/cursos/letras-portugues-ingles-2a-licenciatura/",
    type: "EAD",
    certificate: "2ª Licenciatura",
  },
  {
    id: "let-ing-port-lic-out",
    name: "Letras Português/Inglês",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/letras_.jpg",
    url: "https://ead.unimar.br/cursos/letras-portugues-ingles/",
    type: "EAD",
    certificate: "Licenciatura",
  },
  {
    id: "log-out",
    name: "Logística",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/logistica.jpg.webp",
    url: "https://ead.unimar.br/cursos/logistica/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "market-out",
    name: "Marketing",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/marketing.jpg",
    url: "https://ead.unimar.br/cursos/marketing/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "market-dig-out",
    name: "Marketing Digital",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/marketing-digital.jpg",
    url: "https://ead.unimar.br/cursos/marketing-digital/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "ped-2-lic-out",
    name: "Pedagogia",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/pedadogia.jpg.webp",
    url: "https://ead.unimar.br/cursos/pedagogia-2a-licenciatura/",
    type: "EAD",
    certificate: "2ª Licenciatura",
  },
  {
    id: "ped-lic-out",
    name: "Pedagogia",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/pedadogia.jpg.webp",
    url: "https://ead.unimar.br/cursos/pedagogia/",
    type: "EAD",
    certificate: "Licenciatura",
  },
  {
    id: "proc-ger-out",
    name: "Processos Gerenciais",
    photo: "https://ead.unimar.br/wp-content/uploads/2020/09/processos-gerenciais.jpg",
    url: "https://ead.unimar.br/cursos/processos-gerenciais/",
    type: "EAD",
    certificate: "Superior Tecnológico",
  },
  {
    id: "serv-soc-out",
    name: "Serviço Social",
    photo: "https://ead.unimar.br/wp-content/uploads/2022/12/h4wyqgkewrc-scaled.jpg",
    url: "htthttps://ead.unimar.br/cursos/servico-social/",
    type: "EAD",
    certificate: "Bacharelado",
  },
]